version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_HOST: localhost
  MYSQL_ROOT_PASSWORD: root
  REACT_APP_SERVER_PORT: 8000

services:

  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - datavolume:/var/lib/mysql

  mysql-test:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_DATABASE: db-test
    ports:
      - 3310:3306
    restart: unless-stopped
    volumes:
      - datavolume-test:/var/lib/mysql

  server:
    build: ./server
    image: 'server'
    depends_on:
      - mysql
    expose:
      - 8000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
      MYSQL_DATABASE: db
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    links:
      - mysql
    command: yarn start

  server-test:
    image: 'server'
    depends_on:
      - mysql
      - server
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-test
      MYSQL_DATABASE: db-test
    command: yarn test

  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: yarn start

volumes:
  datavolume:
  datavolume-test: